version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL} # This should be set to the production database URL
